### ISSUE TITLE
error creating device tree with stock recovery from Xiaomi Mi MIX 2

### ISSUE THREAD

**Issue by nextgen-networks** [TwrpBuilder/twrpbuilder_tree_generator#1]
java -jar TwrpBuilder-1.0-SNAPSHOT.jar -r C:\Users\lenovo\Downloads\01_Software\01_MobileDevices\01_Android\TWRPbuilder\chiron\recovery.img -otg
Building tree using: C:\Users\lenovo\Downloads\01_Software\01_MobileDevices\01_Android\TWRPbuilder\chiron\recovery.img
java.lang.NullPointerException
        at com.github.twrpbuilder.util.GetAsset.run(GetAsset.java:40)
        at com.github.twrpbuilder.util.GetAsset.<init>(GetAsset.java:12)
        at com.github.twrpbuilder.util.RunCode.<init>(RunCode.java:22)
        at com.github.twrpbuilder.MainActivity.usePosixParser(MainActivity.java:116)
        at com.github.twrpbuilder.MainActivity.main(MainActivity.java:219)
java.lang.NullPointerException
        at com.github.twrpbuilder.util.GetAsset.run(GetAsset.java:40)
        at com.github.twrpbuilder.util.GetAsset.<init>(GetAsset.java:12)
        at com.github.twrpbuilder.util.RunCode.<init>(RunCode.java:23)
        at com.github.twrpbuilder.MainActivity.usePosixParser(MainActivity.java:116)
        at com.github.twrpbuilder.MainActivity.main(MainActivity.java:219)
creating directory: C:\Users\lenovo\Downloads\01_Software\01_MobileDevices\01_Android\TWRPbuilder\tmp
Dir created: tmp\

recovery image extracted from: chiron_global_images_V9.5.4.0.ODEMIFA_20180315.0000.00_8.0_global_d8f2f1f5fb.tgz

TwrpBuilder Version:
untagged-f9a9648fe27192394c39

Tested with:

- HP Tablet - Windows 10 Enterprise 1709 64bit & java runtime 8 build 161
- Lenovo Tablet - Windows 10 Pro 1803 64bit & java runtime 8 build 161

**Comment by KaustubhPatange** [comment]
@nextgen-networks Even I got the same error. I tried -t mt argument but still no luck. Assets are not properly extracting I guess.

**Comment by androidlover5842** [comment]
not works for windows

**Comment by androidlover5842** [comment]
it only works for linux based os .

**Comment by nextgen-networks** [comment]
@androidlover5842 Thanks for the fast feedback and your grat work!

Would be fantastic to have this hint in the readme.md ;-)

**Comment by androidlover5842** [comment]
sure :)

**Comment by nextgen-networks** [comment]
Hey @androidlover5842 

Tried it today on Ubuntu 16.04

`raupe@nextgen-droid:~/android/twrpbuilder_tree_generator$ java -jar TwrpBuilder.jar -r recovery.img
Building tree using: recovery.img
java.nio.file.NoSuchFileException: recovery.img
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at com.github.twrpbuilder.util.ShellExecutor.cp(ShellExecutor.java:131)
        at com.github.twrpbuilder.MainActivity.usePosixParser(MainActivity.java:99)
        at com.github.twrpbuilder.MainActivity.main(MainActivity.java:224)
creating directory: /home/raupe/android/twrpbuilder_tree_generator/tmp
Dir created: tmp/
failed to uncompress ramdisk
`

**Comment by androidlover5842** [comment]
it's a bug for now rename recovery.img to MiMax.img
