### ISSUE TITLE
failed to uncompress ramdisk on Windows 10 LTSB

### ISSUE THREAD

**Issue by RuthlessRuler** [TwrpBuilder/twrpbuilder_tree_generator#6]
Using Windows 10 LTSB 2016, I am getting failed to uncompress ramdisk.

C:\Users\RuthlessRuler\Downloads\New folder>java -jar TwrpBuilder.jar -aik -r recovery.img
Building tree using: recovery.img
Using Android Image Kitchen to extract recovery.img
java.lang.Exception: Cannot get resource "\bin" from Jar file.
        at com.github.twrpbuilder.Interface.Tools.extract(Tools.java:290)
        at com.github.twrpbuilder.Thread.RunCode.<init>(RunCode.java:20)
        at com.github.twrpbuilder.MainActivity.usePosixParser(MainActivity.java:84)
        at com.github.twrpbuilder.MainActivity.main(MainActivity.java:183)
java.lang.Exception: Cannot get resource "\unpackimg.sh" from Jar file.
        at com.github.twrpbuilder.Interface.Tools.extract(Tools.java:290)
        at com.github.twrpbuilder.Thread.RunCode.<init>(RunCode.java:21)
        at com.github.twrpbuilder.MainActivity.usePosixParser(MainActivity.java:84)
        at com.github.twrpbuilder.MainActivity.main(MainActivity.java:183)
java.io.IOException: Cannot run program "/bin/bash": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.github.twrpbuilder.Interface.Tools.command(Tools.java:39)
        at com.github.twrpbuilder.mkTree.MakeTree.extractKernel(MakeTree.java:114)
        at com.github.twrpbuilder.mkTree.MakeTree.<init>(MakeTree.java:36)
        at com.github.twrpbuilder.Thread.RunCode.run(RunCode.java:62)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 8 more

java.io.IOException: Cannot run program "/bin/bash": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.github.twrpbuilder.Interface.Tools.command(Tools.java:39)
        at com.github.twrpbuilder.mkTree.MakeTree.extractFstab(MakeTree.java:156)
        at com.github.twrpbuilder.mkTree.MakeTree.<init>(MakeTree.java:39)
        at com.github.twrpbuilder.Thread.RunCode.run(RunCode.java:62)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 8 more
failed to uncompress ramdisk

**Comment by surendrajat** [comment]
This tool can only be used on a linux system. Either get a shell in Windows or create a VM.

**Comment by Dyneteve** [comment]
Closed
